### ISSUE TITLE
bro plz help how to add premium on profile.js

### ISSUE THREAD

**Issue by anshuljai** [jauhari21/animo-bot#1]
please tell code

**Comment by jauhari21** [comment]
> please tell code

https://github.com/Nurutomo/wabot-aq/issues/263#issuecomment-839378437

**Comment by jauhari21** [comment]
> please tell code

![Uploading IMG_20210512_164654.jpg…]()

**Comment by jauhari21** [comment]
> please tell code

![IMG_20210512_164654](https://user-images.githubusercontent.com/81492529/117955076-dacc4b80-b341-11eb-90ea-1dbaca73be71.jpg)
![IMG_20210512_164723](https://user-images.githubusercontent.com/81492529/117955084-dbfd7880-b341-11eb-8dee-eb9804fa3ce5.jpg)

let premium = global.prems.map(v => v.replace(/[^0-9]/g, '') + '@s.whatsapp.net').includes(m.sender)

Premium : ${premium ? 'YES':'NO'}

**Comment by anshuljai** [comment]
ok tq kak

**Comment by anshuljai** [comment]
> > please tell code
> 
> ![IMG_20210512_164654](https://user-images.githubusercontent.com/81492529/117955076-dacc4b80-b341-11eb-90ea-1dbaca73be71.jpg)
> ![IMG_20210512_164723](https://user-images.githubusercontent.com/81492529/117955084-dbfd7880-b341-11eb-8dee-eb9804fa3ce5.jpg)
> 
> let premium = global.prems.map(v => v.replace(/[^0-9]/g, '') + '@s.whatsapp.net').includes(m.sender)
> 
> Premium : ${premium ? 'YES':'NO'}

also send sn code

**Comment by anshuljai** [comment]
@jauhari21
